#!/usr/bin/env bash
set -eu
indir=tmp/merge
outdir=tmp/hupo-repo
rm -rf "$outdir"
mkdir -p "$outdir"
ls -1 "$indir" | while IFS= read -r f; do
  echo "$f"
  y="${f%%-*}"
  m="$(printf %s "$f" | sed -E 's/^[^-]+-//;s/-[^-]+$//')"
  d="${f##*-}"
  outdir_day="$outdir/$y/$m/$d"
  mkdir -p "$outdir_day"
  split -d -l 2000 "$indir/$f" "$outdir_day/"
done
ls -1 "$outdir" | while IFS= read -r y; do
  if [ $y -lt 2015 ]; then
    cd "$outdir/$y"
    echo 'Methodology described at: https://cirosantilli.com/cia-2010-covert-communication-websites/expired-domain-trackers' > README.md
    git init
    git add .
    git commit -m 'autogenerated commit'
    git remote add origin "git@github.com:cirosantilli/expired-domain-names-by-day-$y.git"
    git push -f
    cd -
  fi
done
