#!/usr/bin/env bash
# https://www.cirosantilli.com#how-to-develop-ciro-santillis-website
bundle exec jekyll clean
# Build with possibly missing xref2 references and generate the database.
bundle exec jekyll build --trace
# Now that the database is generated, there can be no errors.
CIROSANTILLI_COM_DB_FAIL_ON_MISSING_REF=1 bundle exec jekyll build --trace
