#!/usr/bin/env bash
# https://www.cirosantilli.com#how-to-develop-this-website
asciidoctor \
  --attribute stylesheet! \
  --failure-level info \
  --out-file _site/index.html \
  --verbose \
  README.adoc \
;
