#!/usr/bin/expect -f
set prompt ">>> "
log_user 0
spawn ollama run llama3.2
expect $prompt
send "/set parameter seed 0\r"
expect $prompt
send "/set parameter num_predict 40\r"
expect $prompt
send "What is quantum field theory?\r"
expect -re "\n(.*?)$prompt"
puts -nonewline $expect_out(1,string)
send -- "/bye"
