#!/usr/bin/env bash
# https://www.cirosantilli.com#how-to-develop-ciro-santillis-website
set -eux
rootdir="$(pwd)"
outdir="${rootdir}/publish"
mkdir -p "$outdir"
# We maintain a safety clone in this directory,
# to avoid leaking .gitignored files through Jekyll.
cd "$outdir"
if [ ! -d .git ]; then
  git clone --recursive "$rootdir" .
else
  git pull
  git submodule update --init
fi
./build
git -C "$rootdir" push
cp \
  Gemfile \
  Gemfile.lock \
  _config.yml \
  _site/ \
;
cd _site
if [ ! -d .git ]; then
  git init
  git remote add origin git@github.com:cirosantilli/cirosantilli.github.io.git
  git fetch origin
  git reset origin/master
fi
git add .
git commit -m "$(git -C "$rootdir" log -n1 --pretty='%H' dev)"
git push origin master:master
