= www.cirosantilli.com
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

Source for: <https://www.cirosantilli.com>

toc::[]

== About this repo

If you have something to say to me, you can open an issue on this repo, even if it is not related to the repo.

I also use this repo as generic issue tracker for stuff that lacks a decent public issue tracker, e.g. companies / government.

Run local server:

    gem install bundle
    bundle install
    xdg-open http://localhost:4000
    ./run

Update gems:

    bundle update
    git add Gemfile.lock

=== Why I removed Disqus comments from the website in 2019-05-04

Commit: https://github.com/cirosantilli/cirosantilli.github.io/commit/794705a201a79b5128934e69df85e3511655c03f

As I started getting a lot of comments on my home page, mostly about China, I decided that Disqus does not scale, and that it would be more productive long term to remove it and point people to GitHub issues instead.

Upsides of removal:

* Disqus discoverability is bad:
** there is no decent way to search existing issues, you have to do JavaScript infinite loading + Ctrl + F. So every reply that I write is a waste of time, as it will never be seen again. 
** comments don't have: decent URLs, titles, metadata like tags or open / close
* Disqus archival is bad: http://web.archive.org/ does not work, and no one knows how to export the issues: https://www.archiveteam.org/index.php?title=Disqus
* before, I had two places where people could comment, Disqus and GitHub issues. Now there is just one.
* Disqus has ads if you ever reach enough traffic, which I'm not willing to have on my website, especially if I don't get paid for them! It also makes page loads slower, although that likely does not matter much.

Downsides:

* people are more likely to comment on Disqus than to create an issue on GitHub, especially because most people use GitHub professionally. But this has the upside that there will be less shitposts as well.
* with Disqus you can see all issues attached to a page automatically, which is nice. But for as long as I'm around, I intend to just solve the issues, cross link between content and issues and tag things appropriately.

My stance towards China hasn't changed, and China comments and corrections about this website are still welcome as always.

Related issue: https://github.com/cirosantilli/cirosantilli.github.io/issues/37
