#!/usr/bin/env bash
set -eu

# https://stackoverflow.com/questions/360201/how-do-i-kill-background-processes-jobs-when-my-shell-script-exits
trap 'kill $(jobs -p)' EXIT

# Do the initial Jekyll + Asciidoctor build.
./build

# We used to do:
#     bundle exec jekyll serve -tw
# but this fails because Jekyll would remove your generated index.html
# Having a server is needed to automatically view index.html and to know
# where the root directory is for / links.
cd _site
python -m SimpleHTTPServer &
cd -

# Auto rebuild.
file=README.adoc
atime="$(stat -c %Z "$file")"
ltime="$atime"
while true; do
  atime="$(stat -c %Z "$file")"
  if [ "$atime" != "$ltime" ]; then
    echo "rebuild: ${atime}"
    exit_status=0
    time ./build-adoc || exit_status="$?"
    if [ "$exit_status" -ne 0 ]; then
      echo "BUILD ERROR!"
    fi
    ltime="$atime"
  fi
  sleep 1
done
