#!/usr/bin/env bash
# https://stackoverflow.com/questions/28908319/how-to-clear-jupyter-notebooks-output-in-all-cells-from-the-linux-terminal/47774393#47774393
jupyter nbconvert --clear-output --inplace *.ipynb
